### ISSUE TITLE
Prompt template

### ISSUE THREAD

**Issue by gerald4** [qizhangli/Gradient-based-Jailbreak-Attacks#1]
Hi! 
Thank you for the source code. It's running well.
However, I'm unable to see the prompt template as in the implementation of GCG.
I'd like to know what effect this has on your evaluation. 
Furthermore, do you have an implementation that can have this prompt template?

**Comment by qizhangli** [comment]
Hi!
You can find the prompt implementation at
https://github.com/qizhangli/Gradient-based-Jailbreak-Attacks/blob/392819c950545e09fd5255b616d7b9afebaa11a3/methods/utils.py#L17
It will return '[INST] {harmful query} {adv suffix} [/INST] {target phrase},' which is the same as the implementation in GCG.

**Comment by gerald4** [comment]
Yes, I wondering why you're not including system prompts such as here 
https://github.com/centerforaisafety/HarmBench/blob/bd53883db56d492a8491a881ca69dfc82997a6bc/baselines/model_utils.py#L42

This should be the most realistic setting as users usually interact only with the instruction, while the system prompts are almost always prefixed.

**Comment by qizhangli** [comment]
The default system prompt has been removed in the latest version of Llama-2.  You can refer to [https://github.com/meta-llama/llama/pull/626](url) and [https://github.com/lm-sys/FastChat/commit/7fe5801d5bb1a82eca51cba7fb331cbe6911ecd6](url).
However, you can add a custom system prompt and launch the attack.
